/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import exceptions.UsuarioDuplicadoException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Administrador;
import model.Conductor;
import model.Despachador;
import model.Usuario;
import service.GestorUsuarios;

/**
 * Ventana de administracion de usuarios (RF-03).
 *
 * Cubre las cuatro operaciones: registrar, consultar, modificar y eliminar.
 * Solo la abre el administrador.
 *
 * @author Grupo 6
 */
public class GestionUsuarios extends javax.swing.JDialog {

    private GestorUsuarios gestorUsuarios;
    private DefaultTableModel modeloTabla;

    //Usuario que tiene la sesion abierta, para no dejar que se borre solo
    private Usuario usuarioSesion;

    /**
     * Creates new form GestionUsuarios
     */

    //Constructor
    public GestionUsuarios(java.awt.Frame parent, boolean modal, Usuario usuarioSesion) {
        super(parent, modal);
        initComponents();

        this.usuarioSesion = usuarioSesion;
        gestorUsuarios = new GestorUsuarios();

        setTitle("Gestión de Usuarios");
        setLocationRelativeTo(parent);

        cargarTabla();
        actualizarTabla();
    }

    //Arma las columnas de la tabla
    private void cargarTabla() {

        String columnas[] = {"ID", "Usuario", "Rol"};

        //La tabla es solo de consulta, los cambios van por los botones
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };

        tblUsuarios.setModel(modeloTabla);
        tblUsuarios.setRowHeight(22);
        tblUsuarios.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    }

    //Trae los usuarios de la base y los pone en la tabla
    private void actualizarTabla() {

        try {

            modeloTabla.setRowCount(0);

            for (Usuario usuario : gestorUsuarios.obtenerUsuarios()) {
                modeloTabla.addRow(new Object[]{
                    usuario.getId(),
                    usuario.getUsuario(),
                    usuario.getrol()
                });
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudieron consultar los usuarios.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limpiar() {
        txtUsuario.setText("");
        txtContrasenia.setText("");
        cbRol.setSelectedIndex(0);
        txtUsuario.setEnabled(true);
        tblUsuarios.clearSelection();
        txtUsuario.requestFocus();
    }

    /*
     * Segun el rol escogido se crea la subclase que corresponde. Todas se
     * manejan como Usuario, que es el polimorfismo del modelo.
     */
    private Usuario crearUsuario(String nombre, String clave, String rol) {

        switch (rol) {
            case "Administrador":
                return new Administrador(nombre, clave);
            case "Despachador":
                return new Despachador(nombre, clave);
            default:
                return new Conductor(nombre, clave);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        lblRol = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        lblAyuda = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion de Usuarios"));

        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblContrasenia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContrasenia.setText("Contraseña:");

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRol.setText("Rol:");

        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Despachador", "Conductor" }));

        lblAyuda.setText("Clic en una fila para cargarla");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnAgregar.setText("Agregar");
        btnAgregar.setFocusable(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregar);

        btnModificar.setText("Modificar");
        btnModificar.setFocusable(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFocusable(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        btnCerrar.setText("Cerrar");
        btnCerrar.setFocusable(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUsuario)
                            .addComponent(lblContrasenia)
                            .addComponent(lblRol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAyuda)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuario)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContrasenia)
                            .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRol)
                            .addComponent(cbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAyuda))
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Al hacer clic en una fila se cargan los datos en los campos
    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int fila = tblUsuarios.getSelectedRow();

        if (fila == -1) {
            return;
        }

        txtUsuario.setText(tblUsuarios.getValueAt(fila, 1).toString());
        cbRol.setSelectedItem(tblUsuarios.getValueAt(fila, 2).toString());
        txtContrasenia.setText("");

        //El nombre de usuario no se cambia, es la llave con la que se busca
        txtUsuario.setEnabled(false);
    }//GEN-LAST:event_tblUsuariosMouseClicked

    //Registra un usuario nuevo
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        String nombre = txtUsuario.getText().trim();
        String clave = new String(txtContrasenia.getPassword()).trim();

        if (nombre.isEmpty() || clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe digitar el usuario y la contraseña.");
            return;
        }

        try {

            gestorUsuarios.agregarUsuario(crearUsuario(nombre, clave, cbRol.getSelectedItem().toString()));

            JOptionPane.showMessageDialog(this, "Usuario registrado correctamente");

            actualizarTabla();
            limpiar();

        } catch (UsuarioDuplicadoException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo registrar el usuario.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    //Cambia la contraseña del usuario seleccionado
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (tblUsuarios.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla.");
            return;
        }

        String nombre = txtUsuario.getText().trim();
        String clave = new String(txtContrasenia.getPassword()).trim();

        if (clave.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la contraseña nueva.");
            return;
        }

        try {

            gestorUsuarios.modificarUsuario(crearUsuario(nombre, clave, cbRol.getSelectedItem().toString()));

            JOptionPane.showMessageDialog(this, "Contraseña actualizada");

            actualizarTabla();
            limpiar();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo modificar el usuario.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    //Da de baja al usuario seleccionado
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (tblUsuarios.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un usuario de la tabla.");
            return;
        }

        String nombre = txtUsuario.getText().trim();

        //No tiene sentido que el administrador se de de baja a si mismo
        if (nombre.equals(usuarioSesion.getUsuario())) {
            JOptionPane.showMessageDialog(this,
                    "No puede dar de baja el usuario con el que tiene la sesión abierta.",
                    "Operación no permitida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Desea dar de baja al usuario " + nombre + "?",
                "Confirmar",
                JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        try {

            gestorUsuarios.eliminarUsuario(nombre);

            JOptionPane.showMessageDialog(this, "Usuario dado de baja");

            actualizarTabla();
            limpiar();

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo dar de baja el usuario.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
