/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import exceptions.DatosInvalidosException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Paquete;
import service.GestorIncidencias;

/**
 * Ventana para registrar una incidencia de un paquete (HU-07).
 *
 * El paquete y el vehiculo se muestran solo de lectura porque vienen de la fila
 * que se escogio en el monitor. Los tipos de incidencia se cargan de la tabla
 * tipos_incidencia, no van quemados en el codigo.
 *
 * @author Grupo 6
 */
public class IncidenciaDialog extends javax.swing.JDialog {

    private Principal principal;
    private Paquete paquete;
    private GestorIncidencias gestorIncidencias;

    /**
     * Creates new form IncidenciaDialog
     */

    //Constructor
    public IncidenciaDialog(java.awt.Frame parent, boolean modal, Paquete paquete) {
        super(parent, modal);
        initComponents();

        principal = (Principal) parent;
        this.paquete = paquete;
        gestorIncidencias = new GestorIncidencias();

        setTitle("Registrar Incidencia");
        setLocationRelativeTo(parent);

        //Muestra a que paquete y a que vehiculo se le va a cargar la incidencia
        lblValPaquete.setText(paquete.getId() + " - " + paquete.getDestinatario());

        if (paquete.getVehiculo() != null) {
            lblValVehiculo.setText(paquete.getVehiculo().getPlaca()
                    + " (" + paquete.getVehiculo().getTipo() + ")");
        } else {
            lblValVehiculo.setText("Sin asignar");
        }

        cargarTipos();
    }

    /*
     * Llena la lista con los tipos que estan registrados en la base. Asi, si
     * despues se agrega un tipo nuevo a la tabla, aparece solo en la ventana.
     */
    private void cargarTipos() {

        cbTipo.removeAllItems();

        try {

            for (String tipo : gestorIncidencias.obtenerTipos()) {
                cbTipo.addItem(tipo);
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudieron cargar los tipos de incidencia.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPaquete = new javax.swing.JLabel();
        lblValPaquete = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        lblValVehiculo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Incidencias"));

        lblPaquete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPaquete.setText("Paquete:");

        lblValPaquete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValPaquete.setText("-");

        lblVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVehiculo.setText("Vehículo:");

        lblValVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValVehiculo.setText("-");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setText("Tipo:");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescripcion);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPaquete)
                    .addComponent(lblVehiculo)
                    .addComponent(lblTipo)
                    .addComponent(lblDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaquete)
                    .addComponent(lblValPaquete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo)
                    .addComponent(lblValVehiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Guarda la incidencia
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtDescripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe describir la incidencia.");
            return;
        }

        if (cbTipo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Debe escoger el tipo de incidencia.");
            return;
        }

        try {

            //El vehiculo puede venir nulo, el gestor se encarga de avisarlo
            String placa = null;

            if (paquete.getVehiculo() != null) {
                placa = paquete.getVehiculo().getPlaca();
            }

            gestorIncidencias.registrarIncidencia(
                    paquete.getId(),
                    placa,
                    cbTipo.getSelectedItem().toString(),
                    txtDescripcion.getText());

            JOptionPane.showMessageDialog(this, "Incidencia registrada correctamente");

            //Refresca el monitor para que la alerta aparezca de una vez
            principal.actualizarTabla();

            dispose();

        } catch (DatosInvalidosException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo guardar la incidencia.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    //Cierra la ventana
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblPaquete;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblValPaquete;
    private javax.swing.JLabel lblValVehiculo;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
