/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import exceptions.DatosInvalidosException;
import exceptions.PaqueteDuplicadoException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Vehiculo;
import model.Paquete;
import model.EstadoPaquete;
/**
 * 
 * @author Grupo 6
 */
public class PaqueteDialog extends javax.swing.JDialog {

    // Opcion del combo para dejar el paquete sin vehiculo
    private static final String SIN_VEHICULO = "(Sin asignar)";

    private Principal principal;
    private Paquete paqueteEditar;
    private boolean editar = false;

    /**
     * Creates new form PaqueteDialog
     */
    
    //Constructor para registrar paquetes
    public PaqueteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        principal = (Principal) parent;
        setTitle("Registrar Paquete");
        setLocationRelativeTo(parent);
        cargarVehiculos();
        

        
        
    }
    
    //Constructor para modificar
    public PaqueteDialog(java.awt.Frame parent, boolean modal, Paquete paquete ) {
        super(parent, modal);
        initComponents();
        principal = (Principal) parent;
        editar = true;
        setTitle("Modificar Paquete");
        setLocationRelativeTo(parent);
        cargarVehiculos();
        
        //Enseña los datos del paquete
        paqueteEditar = paquete;

        txtId.setText(String.valueOf(paquete.getId()));
        txtId.setEnabled(false);
        txtDestinatario.setText(paquete.getDestinatario());
        txtDireccion.setText(paquete.getDireccion());
        txtPeso.setText(String.valueOf(paquete.getPeso()));
        cbEstado.setSelectedItem(paquete.getEstado().toString());

        if (paquete.getVehiculo() != null) {
            cbVehiculo.setSelectedItem(paquete.getVehiculo().getPlaca());
        } else {
            cbVehiculo.setSelectedItem(SIN_VEHICULO);
        }

    }

    /*
     * Llena el combo con las placas registradas en la base de datos.
     * La primera opcion siempre es "sin asignar", asi el combo nunca queda
     * vacio aunque todavia no haya vehiculos en la flota.
     */
    private void cargarVehiculos() {

        cbVehiculo.removeAllItems();
        cbVehiculo.addItem(SIN_VEHICULO);

        try {

            for (Vehiculo vehiculo : principal.getGestorVehiculos().obtenerVehiculos()) {
                cbVehiculo.addItem(vehiculo.getPlaca());
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo cargar la flota.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDestinatario = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lblVehiculo = new javax.swing.JLabel();
        cbVehiculo = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Paquetes"));

        lblDestinatario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDestinatario.setText("Destinatario:");

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDireccion.setText("Direccion:");

        lblPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPeso.setText("Peso:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDIENTE", "EN_TRANSITO", "ENTREGADO" }));

        lblVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVehiculo.setText("Vehiculo:");

        cbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motocicleta", "Automovil", "Camion", "Furgon" }));

        jToolBar1.setRollover(true);

        btnGuardar.setText("Guardar");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelar);

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblId.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblId)
                    .addComponent(lblVehiculo)
                    .addComponent(lblDestinatario)
                    .addComponent(lblDireccion)
                    .addComponent(lblPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccion)
                    .addComponent(txtPeso)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestinatario)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestinatario)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo)
                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Cierra la ventana
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //Revisa que todos los campos esten completos
        if (txtId.getText().isEmpty()
                || txtDestinatario.getText().isEmpty()
                || txtDireccion.getText().isEmpty()
                || txtPeso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
            return;
        }

        try {

            //El ID y el peso se convierten aqui, dentro del try, porque si el
            //usuario digita letras se lanza NumberFormatException
            int id = Integer.parseInt(txtId.getText().trim());
            double peso = Double.parseDouble(txtPeso.getText().trim());

            /*
             * El vehiculo queda nulo cuando se escoge la opcion sin asignar.
             * Antes se llamaba directo a getSelectedItem().toString() y eso
             * reventaba cuando todavia no habia vehiculos registrados.
             */
            Vehiculo vehiculo = null;
            Object seleccion = cbVehiculo.getSelectedItem();

            if (seleccion != null && !seleccion.toString().equals(SIN_VEHICULO)) {
                vehiculo = principal.getGestorVehiculos().buscarVehiculo(seleccion.toString());
            }

            EstadoPaquete estado = EstadoPaquete.valueOf(cbEstado.getSelectedItem().toString());

            // Crea el paquete
            Paquete paquete = new Paquete(
                    id,
                    txtDestinatario.getText(),
                    txtDireccion.getText(),
                    peso,
                    estado,
                    vehiculo);

            //Modifica o registra los paquetes
            if (editar) {
                principal.getGestorPaquetes().modificarPaquete(paquete);
                JOptionPane.showMessageDialog(this, "Paquete modificado correctamente");
            } else {
                principal.getGestorPaquetes().agregarPaquete(paquete);
                JOptionPane.showMessageDialog(this, "Paquete registrado correctamente");
            }

            //Actualiza la tabla
            principal.actualizarTabla();

            //Cierra la ventana
            dispose();

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this,
                    "El ID y el peso tienen que ser valores numericos.");

        } catch (PaqueteDuplicadoException | DatosInvalidosException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage());

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo guardar el paquete.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblDestinatario;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
