package ui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.GestorPaquetes;
import service.GestorVehiculos;
import model.Paquete;
import service.GestorUsuarios;
import model.EstadoPaquete;
/**
 *
 * @author ssanc
 */
public class Principal extends javax.swing.JFrame {

    private DefaultTableModel TableModel;
    private GestorPaquetes gestorPaquetes;
    private GestorVehiculos gestorVehiculos;
    private GestorUsuarios gestorUsuarios;
  
    
    //Constructor
    public Principal(GestorUsuarios gestorUsuarios,GestorVehiculos gestorVehiculos,GestorPaquetes gestorPaquetes) {
        initComponents();
        
           
           this.gestorUsuarios = gestorUsuarios;
           this.gestorVehiculos = gestorVehiculos;
           this.gestorPaquetes = gestorPaquetes;
    
        setTitle("Sistema de Logistica - Monitor");
        setLocationRelativeTo(null);
        setResizable(false);
        
       
        //Carga y actualiza la tabla
        cargarTabla();
        actualizarTabla();
    }
    
    
    //Carga las columnas de la tabla
    private void cargarTabla() {
        
        String columnas[] = {
            "ID Envio",
            "Ruta",
            "Estado",
            "Asignacion"
        };
        TableModel = new DefaultTableModel(columnas, 0);
        tblPaquetes.setModel(TableModel);
        
    }
    
    //Actualiza los datos de la tabla
    public void actualizarTabla(){
        TableModel.setRowCount(0);
        for(Paquete paquete : gestorPaquetes.obtenerPaquetes()) {
            String asignacion = "";
            if(paquete.getVehiculo() != null) {
                asignacion = paquete.getVehiculo().getPlaca();
                
            }
            TableModel.addRow(new Object[] {
                paquete.getId(),
                paquete.getDireccion(),
                paquete.getEstado(),
                asignacion
            });
        }
        actualizarEstadisticas();
        
    }
    public GestorPaquetes getGestorPaquetes() {
        return gestorPaquetes;
    }

    public GestorVehiculos getGestorVehiculos() {
        return gestorVehiculos;
    }
    
    private void actualizarEstadisticas() {

    int pendientes = 0;
    int enRuta = 0;
    int entregados = 0;

    for (Paquete paquete : gestorPaquetes.obtenerPaquetes()) {

        switch (paquete.getEstado()) {

            case PENDIENTE:
                pendientes++;
                break;

            case EN_TRANSITO:
                enRuta++;
                break;

            case ENTREGADO:
                entregados++;
                break;
        }
    }

    txtPendientes.setText(String.valueOf(pendientes));
    txtEnRuta.setText(String.valueOf(enRuta));
    txtEntregadosHoy.setText(String.valueOf(entregados));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblEntregadosHoy = new javax.swing.JLabel();
        lblEnRuta = new javax.swing.JLabel();
        lblPendientes = new javax.swing.JLabel();
        txtEntregadosHoy = new javax.swing.JTextField();
        txtEnRuta = new javax.swing.JTextField();
        txtPendientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlertasCriticas = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnRegistrarVehiculo = new javax.swing.JButton();
        btnRegistrarPaquete = new javax.swing.JButton();
        btnEditarPaquete = new javax.swing.JButton();
        btnEliminarPaquete = new javax.swing.JButton();
        btnVerAlertas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de Logistica - Monitor"));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Monito Principal de Logistica");

        lblEntregadosHoy.setText("Entregados Hoy:");

        lblEnRuta.setText("En Ruta:");

        lblPendientes.setText("Pendientes:");

        tblPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Envio", "Ruta", "Estado", "Asignacion"
            }
        ));
        jScrollPane1.setViewportView(tblPaquetes);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Alerta Criticas"));

        txtAlertasCriticas.setColumns(20);
        txtAlertasCriticas.setRows(5);
        jScrollPane2.setViewportView(txtAlertasCriticas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Estadisticas Rapidas"));

        jLabel5.setText("Proximamente........");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel5)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jToolBar1.setRollover(true);

        btnRegistrarVehiculo.setText("[ Regitrar Vehiculo]");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistrarVehiculo);

        btnRegistrarPaquete.setText("[ Registrar Paquete]");
        btnRegistrarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPaqueteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistrarPaquete);

        btnEditarPaquete.setText("[ Editar Paquete ]");
        btnEditarPaquete.setFocusable(false);
        btnEditarPaquete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarPaquete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPaqueteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditarPaquete);

        btnEliminarPaquete.setText("[ Eliminar Paquete ]");
        btnEliminarPaquete.setFocusable(false);
        btnEliminarPaquete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarPaquete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPaqueteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminarPaquete);

        btnVerAlertas.setText("[ Ver Alertas ]");
        btnVerAlertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlertasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerAlertas);

        btnCerrarSesion.setText("[ Cerrar sesion]");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrarSesion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEntregadosHoy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEntregadosHoy, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEnRuta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPendientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntregadosHoy)
                    .addComponent(lblEnRuta)
                    .addComponent(lblPendientes)
                    .addComponent(txtEntregadosHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        miAcercaDe.setText("Acerca de....");
        miAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAcercaDeActionPerformed(evt);
            }
        });
        jMenu2.add(miAcercaDe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cierra la sesion
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    //Abre la ventana del registro del vehiculo
    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        VehiculoDialog dialog = new VehiculoDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    //Muestra las alertas
    private void btnVerAlertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlertasActionPerformed
       
    StringBuilder alertas = new StringBuilder();

    for (Paquete paquete : gestorPaquetes.obtenerPaquetes()) {

        if (paquete.getVehiculo() == null) {
            alertas.append("- El paquete ")
                    .append(paquete.getId())
                    .append(" no tiene vehículo asignado.\n");
        }

        if (paquete.getEstado() == EstadoPaquete.PENDIENTE) {
            alertas.append("- El paquete ")
                    .append(paquete.getId())
                    .append(" está pendiente de entrega.\n");
        }
    }

    if (alertas.length() == 0) {
        JOptionPane.showMessageDialog(this,
                "No existen alertas.");
    } else {
        JOptionPane.showMessageDialog(this,
                alertas.toString(),
                "Alertas",
                JOptionPane.WARNING_MESSAGE);
    }
    
        
    }//GEN-LAST:event_btnVerAlertasActionPerformed

    //Abre la ventana del registro de paquetes
    private void btnRegistrarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPaqueteActionPerformed
        PaqueteDialog dialog = new PaqueteDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnRegistrarPaqueteActionPerformed

    //Abre la ventana de "Acerca de..."
    private void miAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAcercaDeActionPerformed
        AcercaDialog dialog = new AcercaDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_miAcercaDeActionPerformed

    
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    //Cierra la aplicacion
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this, "Desa salir del sistema?", "Salir", JOptionPane.YES_NO_OPTION);
        if(opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
            
        }
    }//GEN-LAST:event_btnSalirActionPerformed
    
    //Edita el paquete 
    private void btnEditarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPaqueteActionPerformed
        int fila = tblPaquetes.getSelectedRow();
        
        if(fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un paquete");
            return;
        }
        
        int id = (int) tblPaquetes.getValueAt(fila, 0);
        
        Paquete paquete = gestorPaquetes.buscarPaquete(id);
        
        if(paquete != null) {
            PaqueteDialog dialog = new PaqueteDialog(this, true, paquete);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_btnEditarPaqueteActionPerformed

    //Elimina el paquete
    private void btnEliminarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPaqueteActionPerformed
        int fila = tblPaquetes.getSelectedRow();
        
        if(fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un paquete");
            return;
            
        }
        
        int id = (int) tblPaquetes.getValueAt(fila, 0);
        int opcion = JOptionPane.showConfirmDialog(this, "Desea eliminar este paquete", "Confimar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_NO_OPTION) {
            
            gestorPaquetes.eliminarPaquete(id);
            actualizarTabla();
            
            JOptionPane.showMessageDialog(this, "Paquete eliminado");
        }
    }//GEN-LAST:event_btnEliminarPaqueteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {

            GestorUsuarios gestorUsuarios = new GestorUsuarios();
            GestorVehiculos gestorVehiculos = new GestorVehiculos();
            GestorPaquetes gestorPaquetes = new GestorPaquetes();

            new Principal(
                    gestorUsuarios,
                    gestorVehiculos,
                    gestorPaquetes
            ).setVisible(true);

        }

    });

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarPaquete;
    private javax.swing.JButton btnEliminarPaquete;
    private javax.swing.JButton btnRegistrarPaquete;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JButton btnVerAlertas;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEnRuta;
    private javax.swing.JLabel lblEntregadosHoy;
    private javax.swing.JLabel lblPendientes;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JMenuItem miAcercaDe;
    private javax.swing.JTable tblPaquetes;
    private javax.swing.JTextArea txtAlertasCriticas;
    private javax.swing.JTextField txtEnRuta;
    private javax.swing.JTextField txtEntregadosHoy;
    private javax.swing.JTextField txtPendientes;
    // End of variables declaration//GEN-END:variables
}
