/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.Usuario;
import model.Vehiculo;
import service.GestorUbicaciones;
import service.GestorVehiculos;

/**
 * Ventana para que el conductor reporte su ubicacion desde el sistema (RF-12).
 *
 * Las coordenadas se digitan planas, en dos campos: latitud y longitud. Cada
 * envio agrega una fila nueva en ubicaciones_vehiculo, de manera que queda el
 * historico del recorrido y no solo la ultima posicion.
 *
 * La ventana se queda abierta despues de enviar, para que el conductor pueda
 * mandar varios reportes seguidos mientras avanza en la ruta.
 *
 * @author Grupo 6
 */
public class UbicacionDialog extends javax.swing.JDialog {

    private Principal principal;
    private Usuario conductor;
    private GestorVehiculos gestorVehiculos;
    private GestorUbicaciones gestorUbicaciones;

    //Cuantos reportes lleva mandados en esta sesion
    private int reportesEnviados = 0;

    /**
     * Creates new form UbicacionDialog
     */

    //Constructor
    public UbicacionDialog(java.awt.Frame parent, boolean modal, Usuario conductor) {
        super(parent, modal);
        initComponents();

        principal = (Principal) parent;
        this.conductor = conductor;
        gestorVehiculos = new GestorVehiculos();
        gestorUbicaciones = new GestorUbicaciones();

        setTitle("Enviar Ubicación");
        setLocationRelativeTo(parent);

        lblValConductor.setText(conductor.getUsuario());

        cargarVehiculos();
    }

    /*
     * Llena el combo unicamente con los vehiculos que tiene asignados este
     * conductor. Asi no puede reportar por un vehiculo que no maneja.
     */
    private void cargarVehiculos() {

        cbVehiculo.removeAllItems();

        try {

            for (Vehiculo vehiculo : gestorVehiculos.obtenerVehiculosDeConductor(conductor.getUsuario())) {
                cbVehiculo.addItem(vehiculo.getPlaca() + " (" + vehiculo.getTipo() + ")");
            }

            if (cbVehiculo.getItemCount() == 0) {

                JOptionPane.showMessageDialog(this,
                        "El usuario " + conductor.getUsuario() + " no tiene vehiculos asignados.\n"
                        + "El administrador debe asignarle uno para poder reportar la ubicacion.",
                        "Sin vehiculo",
                        JOptionPane.WARNING_MESSAGE);

                btnEnviar.setEnabled(false);
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo cargar la flota del conductor.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);

            btnEnviar.setEnabled(false);
        }
    }

    /*
     * Del texto del combo se saca solo la placa, que es lo que va antes del
     * parentesis. Ejemplo: de "CRC-001 (Automovil)" saca "CRC-001".
     */
    private String obtenerPlacaSeleccionada() {
        return cbVehiculo.getSelectedItem().toString().split(" ")[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblConductor = new javax.swing.JLabel();
        lblValConductor = new javax.swing.JLabel();
        lblVehiculo = new javax.swing.JLabel();
        cbVehiculo = new javax.swing.JComboBox<>();
        lblLatitud = new javax.swing.JLabel();
        txtLatitud = new javax.swing.JTextField();
        lblLongitud = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        lblAyuda = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnEnviar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reporte de Ubicacion"));

        lblConductor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblConductor.setText("Conductor:");

        lblValConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValConductor.setText("-");

        lblVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVehiculo.setText("Vehículo:");

        lblLatitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLatitud.setText("Latitud:");

        lblLongitud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLongitud.setText("Longitud:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText("Estado:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En ruta", "Disponible" }));

        lblAyuda.setText("Ejemplo: 9.9333300 y -84.0833300");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnEnviar.setText("Enviar");
        btnEnviar.setFocusable(false);
        btnEnviar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnviar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEnviar);

        btnCerrar.setText("Cerrar");
        btnCerrar.setFocusable(false);
        btnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCerrar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConductor)
                    .addComponent(lblVehiculo)
                    .addComponent(lblLatitud)
                    .addComponent(lblLongitud)
                    .addComponent(lblEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConductor)
                    .addComponent(lblValConductor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehiculo)
                    .addComponent(cbVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLatitud)
                    .addComponent(txtLatitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLongitud)
                    .addComponent(txtLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAyuda)
                .addGap(18, 18, 18)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Manda el reporte de ubicacion
    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        if (txtLatitud.getText().trim().isEmpty() || txtLongitud.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe digitar la latitud y la longitud.");
            return;
        }

        try {

            //Las coordenadas se convierten aqui, dentro del try, por si vienen con letras
            double latitud = Double.parseDouble(txtLatitud.getText().trim());
            double longitud = Double.parseDouble(txtLongitud.getText().trim());

            //Rango valido de coordenadas
            if (latitud < -90 || latitud > 90) {
                JOptionPane.showMessageDialog(this, "La latitud tiene que estar entre -90 y 90.");
                return;
            }

            if (longitud < -180 || longitud > 180) {
                JOptionPane.showMessageDialog(this, "La longitud tiene que estar entre -180 y 180.");
                return;
            }

            String placa = obtenerPlacaSeleccionada();
            String estado = cbEstado.getSelectedItem().toString();

            gestorUbicaciones.registrarUbicacion(placa, latitud, longitud, estado);

            //El vehiculo tambien queda con ese estado en la flota
            gestorVehiculos.cambiarEstado(placa, estado);

            reportesEnviados++;

            JOptionPane.showMessageDialog(this,
                    "Ubicación reportada.\n"
                    + "Vehículo " + placa + " en " + latitud + ", " + longitud + "\n"
                    + "Reportes enviados en esta sesión: " + reportesEnviados);

            //La ventana se queda abierta para seguir reportando la ruta
            txtLatitud.setText("");
            txtLongitud.setText("");
            txtLatitud.requestFocus();

            principal.actualizarTabla();

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this,
                    "La latitud y la longitud tienen que ser valores numericos.\n"
                    + "Se usa el punto como separador decimal, por ejemplo 9.9333300");

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(this,
                    "No se pudo guardar la ubicación.\n" + ex.getLocalizedMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    //Cierra la ventana
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblAyuda;
    private javax.swing.JLabel lblConductor;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblLatitud;
    private javax.swing.JLabel lblLongitud;
    private javax.swing.JLabel lblValConductor;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JTextField txtLatitud;
    private javax.swing.JTextField txtLongitud;
    // End of variables declaration//GEN-END:variables
}
