/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cliente;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.Random;
import javax.swing.JOptionPane;
import model.Configuracion;
import service.GestorConfiguracion;

/**
 * Cliente que representa a un vehiculo de la flota.
 *
 * Se conecta al servidor, se identifica con la placa y a partir de ahi manda su
 * ubicacion cada cierto tiempo desde un hilo aparte. Tambien permite cambiar el
 * estado de los paquetes y reportar incidencias.
 *
 * Se pueden abrir varias instancias al mismo tiempo, cada una con una placa
 * distinta, para probar la concurrencia del servidor.
 *
 * @author Grupo 6
 */
public class ClienteVehiculo extends javax.swing.JFrame {

    /*
     * La direccion del servidor, el puerto y cada cuanto se reporta la
     * ubicacion salen del archivo configuracion.dat, que se lee con
     * serializacion. Asi se cambian sin tocar el codigo.
     */
    private Configuracion configuracion = new GestorConfiguracion().cargarSeguro();

    private DataInputStream in;
    private DataOutputStream out;

    private String placa = "";
    private boolean conectado = false;

    // Posicion simulada del vehiculo, arranca en San Jose centro
    private double latitud = 9.9333300;
    private double longitud = -84.0833300;
    private Random random = new Random();

    /**
     * Creates new form ClienteVehiculo
     */

    //Constructor
    public ClienteVehiculo() {
        initComponents();
        setTitle("QuickDelivery - Cliente Vehiculo");
        setLocationRelativeTo(null);

        //Los controles se activan hasta que el servidor acepte la placa
        habilitarControles(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEstado = new javax.swing.JLabel();
        lblEstadoConexion = new javax.swing.JLabel();
        lblPaquetes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaquetes = new javax.swing.JTextArea();
        lblBitacora = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBitacora = new javax.swing.JTextArea();
        lblPaquete = new javax.swing.JLabel();
        txtIdPaquete = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        btnEstado = new javax.swing.JButton();
        cbTipoIncidencia = new javax.swing.JComboBox<>();
        btnIncidencia = new javax.swing.JButton();
        btnUbicacion = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente Vehiculo"));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstado.setText("Estado:");

        lblEstadoConexion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoConexion.setText("Sin conexion");

        lblPaquetes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPaquetes.setText("Paquetes asignados:");

        txtPaquetes.setEditable(false);
        txtPaquetes.setColumns(20);
        txtPaquetes.setRows(5);
        jScrollPane1.setViewportView(txtPaquetes);

        lblBitacora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBitacora.setText("Bitacora:");

        txtBitacora.setEditable(false);
        txtBitacora.setColumns(20);
        txtBitacora.setRows(5);
        jScrollPane2.setViewportView(txtBitacora);

        lblPaquete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPaquete.setText("Paquete:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EN_TRANSITO", "ENTREGADO", "PENDIENTE" }));

        btnEstado.setText("Cambiar estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        cbTipoIncidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Retraso", "Averia", "Otro" }));

        btnIncidencia.setText("Reportar incidencia");
        btnIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncidenciaActionPerformed(evt);
            }
        });

        btnUbicacion.setText("Enviar ubicacion");
        btnUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbicacionActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar lista");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(lblPaquetes)
                    .addComponent(lblBitacora)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstadoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPaquete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEstado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbTipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIncidencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUbicacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(lblEstadoConexion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPaquetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBitacora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaquete)
                    .addComponent(txtIdPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncidencia)
                    .addComponent(btnUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cambia el estado del paquete seleccionado
    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        cambiarEstadoPaquete();
    }//GEN-LAST:event_btnEstadoActionPerformed

    //Reporta una incidencia del paquete seleccionado
    private void btnIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncidenciaActionPerformed
        reportarIncidencia();
    }//GEN-LAST:event_btnIncidenciaActionPerformed

    //Manda la ubicacion sin esperar al envio automatico
    private void btnUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbicacionActionPerformed
        enviarUbicacion();
    }//GEN-LAST:event_btnUbicacionActionPerformed

    //Le pide al servidor la lista de paquetes del vehiculo
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        escribir("PAQUETES");
    }//GEN-LAST:event_btnActualizarActionPerformed

    //Avisa al servidor y cierra el cliente
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        escribir("SALIR");
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /*
     * Se conecta al servidor y se queda leyendo lo que llegue. Este metodo se
     * ejecuta en un hilo aparte para no congelar la ventana.
     */
    public void conectar() {

        try {

            Socket socket = new Socket(configuracion.getServidor(), configuracion.getPuerto());

            in = new DataInputStream(socket.getInputStream());
            out = new DataOutputStream(socket.getOutputStream());

            anotar("Conectado al servidor " + configuracion.getServidor() + ":" + configuracion.getPuerto());

            while (true) {

                String mensaje = in.readUTF();

                if (mensaje.startsWith("SUBMITPLACA")) {

                    placa = JOptionPane.showInputDialog(this, "Digite la placa del vehiculo:");

                    if (placa == null || placa.trim().isEmpty()) {
                        escribir("SALIR");
                        System.exit(0);
                    }

                    placa = placa.trim();
                    escribir(placa);

                } else if (mensaje.startsWith("PLACANOEXISTE")) {

                    JOptionPane.showMessageDialog(this,
                            "La placa " + placa + " no esta registrada en la flota.");

                } else if (mensaje.startsWith("PLACAENUSO")) {

                    JOptionPane.showMessageDialog(this,
                            "El vehiculo " + placa + " ya tiene una conexion abierta.");

                } else if (mensaje.startsWith("PLACAACEPTADA")) {

                    conectado = true;
                    setTitle("QuickDelivery - Vehiculo " + placa);
                    lblEstadoConexion.setText("En linea con la placa " + placa);
                    habilitarControles(true);
                    anotar("El servidor acepto la placa " + placa);

                    // A partir de aqui el vehiculo empieza a reportar solo
                    iniciarEnvioUbicacion();

                } else if (mensaje.startsWith("PAQUETES")) {

                    txtPaquetes.setText(mensaje.substring(9));

                } else if (mensaje.startsWith("FLOTA")) {

                    anotar("Otro vehiculo reporto: " + mensaje.substring(6));

                } else if (mensaje.startsWith("OK")) {

                    anotar(mensaje.substring(3));

                } else if (mensaje.startsWith("ERROR")) {

                    anotar("Error: " + mensaje.substring(6));
                }
            }

        } catch (IOException ex) {
            conectado = false;
            habilitarControles(false);
            lblEstadoConexion.setText("Se perdio la conexion");
            anotar("Se perdio la conexion con el servidor: " + ex.getLocalizedMessage());
        }
    }

    /*
     * Hilo que manda la ubicacion cada cierto tiempo sin que el conductor tenga
     * que hacer nada (RF-11). La posicion se mueve un poco en cada envio para
     * simular que el vehiculo va avanzando.
     */
    private void iniciarEnvioUbicacion() {

        Thread hiloUbicacion = new Thread(new Runnable() {
            @Override
            public void run() {

                while (conectado) {

                    try {
                        Thread.sleep(configuracion.getIntervaloUbicacion());
                    } catch (InterruptedException ex) {
                        anotar("Envio automatico interrumpido: " + ex.getLocalizedMessage());
                    }

                    if (conectado) {
                        enviarUbicacion();
                    }
                }
            }
        });

        hiloUbicacion.start();
    }

    private void enviarUbicacion() {

        // Movimiento pequeño para simular el recorrido
        latitud = latitud + (random.nextInt(200) - 100) / 100000.0;
        longitud = longitud + (random.nextInt(200) - 100) / 100000.0;

        escribir("UBICACION;" + latitud + ";" + longitud);
    }

    private void cambiarEstadoPaquete() {

        if (txtIdPaquete.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero del paquete.");
            return;
        }

        try {

            int idPaquete = Integer.parseInt(txtIdPaquete.getText().trim());

            escribir("ESTADO;" + idPaquete + ";" + cbEstado.getSelectedItem().toString());

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El numero del paquete tiene que ser numerico.");
        }
    }

    private void reportarIncidencia() {

        if (txtIdPaquete.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero del paquete.");
            return;
        }

        try {

            int idPaquete = Integer.parseInt(txtIdPaquete.getText().trim());

            String descripcion = JOptionPane.showInputDialog(this, "Describa la incidencia:");

            if (descripcion == null || descripcion.trim().isEmpty()) {
                return;
            }

            // El punto y coma es el separador del protocolo, se quita
            descripcion = descripcion.replace(";", ",");

            escribir("INCIDENCIA;" + idPaquete + ";"
                    + cbTipoIncidencia.getSelectedItem().toString() + ";" + descripcion);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El numero del paquete tiene que ser numerico.");
        }
    }

    // Manda un mensaje al servidor
    private void escribir(String mensaje) {

        try {

            if (out != null) {
                out.writeUTF(mensaje);
            }

        } catch (IOException ex) {
            anotar("No se pudo enviar el mensaje: " + ex.getLocalizedMessage());
        }
    }

    private void anotar(String texto) {
        txtBitacora.append(texto + "\n");
    }

    private void habilitarControles(boolean activo) {
        txtIdPaquete.setEnabled(activo);
        cbEstado.setEnabled(activo);
        cbTipoIncidencia.setEnabled(activo);
        btnUbicacion.setEnabled(activo);
        btnEstado.setEnabled(activo);
        btnIncidencia.setEnabled(activo);
        btnActualizar.setEnabled(activo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                ClienteVehiculo clienteVehiculo = new ClienteVehiculo();
                clienteVehiculo.setVisible(true);

                // La conexion corre en su propio hilo, igual que en el ejemplo
                // del chat visto en clase
                new Thread(() -> clienteVehiculo.conectar()).start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnIncidencia;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUbicacion;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipoIncidencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBitacora;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoConexion;
    private javax.swing.JLabel lblPaquete;
    private javax.swing.JLabel lblPaquetes;
    private javax.swing.JTextArea txtBitacora;
    private javax.swing.JTextField txtIdPaquete;
    private javax.swing.JTextArea txtPaquetes;
    // End of variables declaration//GEN-END:variables
}
